#import <Cocoa/Cocoa.h>

// Go callbacks (implemented in main.go via //export; prototypes generated by
// cgo into _cgo_export.h, which is implicitly included).
extern void goOnReady(void);
extern void goProviderSelected(const char *providerID);
extern void goRefreshRequested(void);
extern void goSaveCredentials(const char *provider, const char *field, const char *value);
extern void goQuitRequested(void);

// ---------------------------------------------------------------------------
// UsagePanelController: two-column popover content (sidebar + content area).
// Declared before OCGAppDelegate so the latter can alloc/init it.
// ---------------------------------------------------------------------------

@interface UsagePanelController : NSViewController
@property(strong) NSView *sidebar;
@property(strong) NSView *content;
@property(strong) NSMutableDictionary<NSString *, NSButton *> *providerButtons;
@property(strong) NSDictionary *state;
@property BOOL settingsVisible;
@property(strong) NSMutableDictionary<NSString *, NSTextField *> *fieldInputs;
@end

@implementation UsagePanelController

- (instancetype)init {
  self = [super initWithNibName:nil bundle:nil];
  if (self) {
    _providerButtons = [NSMutableDictionary dictionary];
    _fieldInputs = [NSMutableDictionary dictionary];
    _settingsVisible = NO;
  }
  return self;
}

- (void)loadView {
  NSRect frame = NSMakeRect(0, 0, 220, 300);
  self.view = [[NSView alloc] initWithFrame:frame];
  // Single unified background across the whole popover — no sidebar tint.
  self.view.wantsLayer = YES;
  self.view.layer.backgroundColor = [NSColor windowBackgroundColor].CGColor;

  self.sidebar = [[NSView alloc] initWithFrame:NSZeroRect];
  self.sidebar.translatesAutoresizingMaskIntoConstraints = NO;
  [self.view addSubview:self.sidebar];

  self.content = [[NSView alloc] initWithFrame:NSZeroRect];
  self.content.translatesAutoresizingMaskIntoConstraints = NO;
  [self.view addSubview:self.content];

  // Hairline vertical divider between sidebar and content.
  NSView *divider = [[NSView alloc] initWithFrame:NSZeroRect];
  divider.translatesAutoresizingMaskIntoConstraints = NO;
  divider.wantsLayer = YES;
  divider.layer.backgroundColor = [NSColor separatorColor].CGColor;
  [self.view addSubview:divider];

  [NSLayoutConstraint activateConstraints:@[
    [self.sidebar.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],
    [self.sidebar.topAnchor constraintEqualToAnchor:self.view.topAnchor],
    [self.sidebar.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor],
    [self.sidebar.widthAnchor constraintEqualToConstant:48],
    [divider.leadingAnchor constraintEqualToAnchor:self.sidebar.trailingAnchor],
    [divider.topAnchor constraintEqualToAnchor:self.view.topAnchor],
    [divider.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor],
    [divider.widthAnchor constraintEqualToConstant:1],
    [self.content.leadingAnchor constraintEqualToAnchor:divider.trailingAnchor],
    [self.content.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],
    [self.content.topAnchor constraintEqualToAnchor:self.view.topAnchor],
    [self.content.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor],
  ]];
}

- (void)viewWillAppear {
  [super viewWillAppear];
  [self renderAll];
}

- (void)updateWithStateJSON:(NSString *)json {
  NSData *data = [json dataUsingEncoding:NSUTF8StringEncoding];
  NSDictionary *parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
  if (![parsed isKindOfClass:[NSDictionary class]]) {
    return;
  }
  self.state = parsed;
  if (self.viewIfLoaded != nil) {
    [self renderAll];
  }
}

- (void)renderAll {
  [self renderSidebar];
  if (self.settingsVisible) {
    [self renderSettings];
  } else {
    [self renderUsage];
  }
}

// ---------- sidebar ----------

- (void)renderSidebar {
  for (NSView *view in [self.sidebar.subviews copy]) {
    [view removeFromSuperview];
  }
  [self.providerButtons removeAllObjects];

  NSArray *providers = self.state[@"providers"] ?: @[];
  NSString *active = self.state[@"active"] ?: @"";
  NSView *previous = nil;
  for (NSDictionary *provider in providers) {
    NSString *providerID = provider[@"id"] ?: @"";
    NSButton *button = [NSButton buttonWithTitle:@""
                                          target:self
                                          action:@selector(providerClicked:)];
    button.image = [self logoImageForProvider:providerID];
    button.imagePosition = NSImageOnly;
    button.bordered = NO;
    BOOL isActive = [providerID isEqualToString:active];
    button.contentTintColor = isActive ? [NSColor systemTealColor] : [NSColor secondaryLabelColor];
    button.identifier = providerID;
    button.translatesAutoresizingMaskIntoConstraints = NO;
    button.wantsLayer = YES;
    button.layer.cornerRadius = 6;
    if (isActive) {
      button.layer.backgroundColor = [[NSColor labelColor] colorWithAlphaComponent:0.08].CGColor;
    }
    [self.sidebar addSubview:button];
    self.providerButtons[providerID] = button;

    NSMutableArray *constraints = [NSMutableArray array];
    [constraints addObject:[button.centerXAnchor constraintEqualToAnchor:self.sidebar.centerXAnchor]];
    [constraints addObject:[button.widthAnchor constraintEqualToConstant:36]];
    [constraints addObject:[button.heightAnchor constraintEqualToConstant:32]];
    if (previous == nil) {
      [constraints addObject:[button.topAnchor constraintEqualToAnchor:self.sidebar.topAnchor constant:12]];
    } else {
      [constraints addObject:[button.topAnchor constraintEqualToAnchor:previous.bottomAnchor constant:6]];
    }
    [NSLayoutConstraint activateConstraints:constraints];
    previous = button;
  }
}

// logoImageForProvider returns a template NSImage built from the provider's
// brand logo SVG path (single-path, viewBox 0 0 24 24, sourced from
// @lobehub/icons Mono variants). Template mode lets contentTintColor recolour
// it for active/inactive states.
- (NSImage *)logoImageForProvider:(NSString *)providerID {
  NSString *path = [self logoPathForProvider:providerID];
  if (path == nil) {
    return [NSImage imageWithSystemSymbolName:@"circle" accessibilityDescription:providerID];
  }
  NSString *svg = [NSString stringWithFormat:
      @"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" "
      @"fill=\"black\" fill-rule=\"evenodd\"><path d=\"%@\"/></svg>", path];
  NSData *svgData = [svg dataUsingEncoding:NSUTF8StringEncoding];
  NSImage *image = [[NSImage alloc] initWithData:svgData];
  image.template = YES;
  return image;
}

// logoPathForProvider returns the SVG path data for each provider's brand logo.
- (NSString *)logoPathForProvider:(NSString *)providerID {
  static NSDictionary *paths = nil;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    paths = @{
      @"opencode" :
          @"M16 6H8v12h8V6zm4 16H4V2h16v20z",
      @"deepseek" :
          @"M23.748 4.482c-.254-.124-.364.113-.512.234-.051.039-.094.09-.137.136-"
          @".372.397-.806.657-1.373.626-.829-.046-1.537.214-2.163.848-.133-.782-"
          @".575-1.248-1.247-1.548-.352-.156-.708-.311-.955-.65-.172-.241-.219-"
          @".51-.305-.774-.055-.16-.11-.323-.293-.35-.2-.031-.278.136-.356.276-"
          @".313.572-.434 1.202-.422 1.84.027 1.436.633 2.58 1.838 3.393.137.093.172.187.129.323-"
          @".082.28-.18.552-.266.833-.055.179-.137.217-.329.14a5.526 5.526 0 01-1.736-1.18c-"
          @".857-.828-1.631-1.742-2.597-2.458a11.365 11.365 0 00-.689-.471c-.985-.957.13-1.743.388-1.836.27-"
          @".098.093-.432-.779-.428-.872.004-1.67.295-2.687.684a3.055 3.055 0 01-.465.137 9.597 9.597 0 00-2.883-"
          @".102c-1.885.21-3.39 1.102-4.497 2.623C.082 8.606-.231 10.684.152 12.85c.403 2.284 1.569 4.175 3.36 "
          @"5.653 1.858 1.533 3.997 2.284 6.438 2.14 1.482-.085 3.133-.284 4.994-1.86.47.234.962.327 1.78.397.63.059 "
          @"1.236-.03 1.705-.128.735-.156.684-.837.419-.961-2.155-1.004-1.682-.595-2.113-.926 1.096-1.296 "
          @"2.746-2.642 3.392-7.003.05-.347.007-.565 0-.845-.004-.17.035-.237.23-.256a4.173 4.173 0 001.545-"
          @".475c1.396-.763 1.96-2.015 2.093-3.517.02-.23-.004-.467-.247-.588zM11.581 18c-2.089-1.642-3.102-2.183-"
          @"3.52-2.16-.392.024-.321.471-.235.763.09.288.207.486.371.739.114.167.192.416-.113.603-"
          @".673.416-1.842-.14-1.897-.167-1.361-.802-2.5-1.86-3.301-3.307-.774-1.393-1.224-2.887-1.298-4.482-"
          @".02-.386.093-.522.477-.592a4.696 4.696 0 011.529-.039c2.132.312 3.946 1.265 5.468 2.774.868.86 1.525 "
          @"1.887 2.202 2.891.72 1.066 1.494 2.082 2.48 2.914.348.292.625.514.891.677-.802.09-2.14.11-3.054-.614zm1-6.44a"
          @".306.306 0 01.415-.287.302.302 0 01.2.288.306.306 0 01-.31.307.303.303 0 01-.304-.308zm3.11 1.596c-"
          @".2.081-.399.151-.59.16a1.245 1.245 0 01-.798-.254c-.274-.23-.47-.358-.552-.758a1.73 1.73 0 01.016-"
          @".588c.07-.327-.008-.537-.239-.727-.187-.156-.426-.199-.688-.199a.559.559 0 01-.254-.078c-.11-"
          @".054-.2-.19-.114-.358.028-.054.16-.186.192-.21.356-.202.767-.136 1.146.016.352.144.618.408 1.001.782.391.451.462.576.685.914.176.265.336.537.445.848.067.195-.019.354-.25.452z",
      @"minimax" :
          @"M16.278 2c1.156 0 2.093.927 2.093 2.07v12.501a.74.74 0 00.744.709.74.74 0 00.743-.709V9.099a2.06 "
          @"2.06 0 012.071-2.049A2.06 2.06 0 0124 9.1v6.561a.649.649 0 01-.652.645.649.649 0 01-.653-.645V9.1a.762.762 "
          @"0 00-.766-.758.762.762 0 00-.766.758v7.472a2.037 2.037 0 01-2.048 2.026 2.037 2.037 0 01-2.048-2.026v-12.5a.785 "
          @".785 0 00-.788-.753.785.785 0 00-.789.752l-.001 15.904A2.037 2.037 0 0113.441 22a2.037 2.037 0 01-2.048-"
          @"2.026V18.04c0-.356.292-.645.652-.645.36 0 .652.289.652.645v1.934c0 .263.142.506.372.638.23.131.514.131.744 0a.734.734 "
          @"0 00.372-.638V4.07c0-1.143.937-2.07 2.093-2.07zm-5.674 0c1.156 0 2.093.927 2.093 2.07v11.523a.648.648 0 01-.652.645.648.648 "
          @"0 01-.652-.645V4.07a.785.785 0 00-.789-.78.785.785 0 00-.789.78v14.013a2.06 2.06 0 01-2.07 2.048 2.06 2.06 0 01-2.071-2.048V9.1a.762.762 "
          @"0 00-.766-.758.762.762 0 00-.766.758v3.8a2.06 2.06 0 01-2.071 2.049A2.06 2.06 0 010 12.9v-1.378c0-.357.292-.646.652-.646.36 0 .653.29.653.646V12.9c0 "
          @".418.343.757.766.757s.766-.339.766-.757V9.099a2.06 2.06 0 012.07-2.048 2.06 2.06 0 012.071 2.048v8.984c0 .419.343.758.767.758.423 0 .766-.339.766-"
          @".758V4.07c0-1.143.937-2.07 2.093-2.07z",
      @"codex" :
          @"M8.086.457a6.105 6.105 0 013.046-.415c1.333.153 2.521.72 3.564 1.7a.117.117 0 00.107.029c1.408-.346 2.762-.224 4.061.366l.063.03.154.076c1.357.703 2.33 1.77 2.918 3.198.278.679.418 1.388.421 2.126a5.655 5.655 0 01-.18 1.631.167.167 0 00.04.155 5.982 5.982 0 011.578 2.891c.385 1.901-.01 3.615-1.183 5.14l-.182.22a6.063 6.063 0 01-2.934 1.851.162.162 0 00-.108.102c-.255.736-.511 1.364-.987 1.992-1.199 1.582-2.962 2.462-4.948 2.451-1.583-.008-2.986-.587-4.21-1.736a.145.145 0 00-.14-.032c-.518.167-1.04.191-1.604.185a5.924 5.924 0 01-2.595-.622 6.058 6.058 0 01-2.146-1.781c-.203-.269-.404-.522-.551-.821a7.74 7.74 0 01-.495-1.283 6.11 6.11 0 01-.017-3.064.166.166 0 00.008-.074.115.115 0 00-.037-.064 5.958 5.958 0 01-1.38-2.202 5.196 5.196 0 01-.333-1.589 6.915 6.915 0 01.188-2.132c.45-1.484 1.309-2.648 2.577-3.493.282-.188.55-.334.802-.438.286-.12.573-.22.861-.304a.129.129 0 00.087-.087A6.016 6.016 0 015.635 2.31C6.315 1.464 7.132.846 8.086.457zm-.804 7.85a.848.848 0 00-1.473.842l1.694 2.965-1.688 2.848a.849.849 0 001.46.864l1.94-3.272a.849.849 0 00.007-.854l-1.94-3.393zm5.446 6.24a.849.849 0 000 1.695h4.848a.849.849 0 000-1.696h-4.848z",
    };
  });
  return paths[providerID];
}

// ---------- usage view ----------

- (void)renderUsage {
  for (NSView *view in [self.content.subviews copy]) {
    [view removeFromSuperview];
  }

  NSString *active = self.state[@"active"] ?: @"";
  NSDictionary *result = self.state[@"results"][active] ?: @{};
  NSString *titleText = @"Usage";
  for (NSDictionary *provider in self.state[@"providers"]) {
    if ([provider[@"id"] isEqualToString:active]) {
      titleText = provider[@"label"] ?: @"Usage";
      break;
    }
  }

  NSView *headerRow = [self makeHeaderRowWithTitle:titleText];
  headerRow.translatesAutoresizingMaskIntoConstraints = NO;
  [self.content addSubview:headerRow];
  [NSLayoutConstraint activateConstraints:@[
    [headerRow.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:0],
    [headerRow.trailingAnchor constraintEqualToAnchor:self.content.trailingAnchor constant:0],
    [headerRow.topAnchor constraintEqualToAnchor:self.content.topAnchor constant:0],
  ]];

  // Footer with Refresh / Quit, anchored to bottom.
  NSView *footer = [self makeFooterRow];
  footer.translatesAutoresizingMaskIntoConstraints = NO;
  [self.content addSubview:footer];
  [NSLayoutConstraint activateConstraints:@[
    [footer.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:0],
    [footer.trailingAnchor constraintEqualToAnchor:self.content.trailingAnchor constant:0],
    [footer.bottomAnchor constraintEqualToAnchor:self.content.bottomAnchor constant:0],
  ]];

  NSString *updatedAt = self.state[@"updated_at"];
  NSString *updatedText = @"Waiting for data";
  if ([updatedAt isKindOfClass:[NSString class]] && updatedAt.length > 0) {
    updatedText = [NSString stringWithFormat:@"Updated %@", updatedAt];
  }

  NSView *previous = headerRow;
  NSString *error = result[@"error"];
  if ([error isKindOfClass:[NSString class]] && error.length > 0) {
    NSTextField *errLabel =
        [self label:error size:12 weight:NSFontWeightRegular color:[NSColor secondaryLabelColor]];
    errLabel.translatesAutoresizingMaskIntoConstraints = NO;
    [self.content addSubview:errLabel];
    [NSLayoutConstraint activateConstraints:@[
      [errLabel.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:16],
      [errLabel.trailingAnchor constraintEqualToAnchor:self.content.trailingAnchor constant:-16],
      [errLabel.topAnchor constraintEqualToAnchor:previous.bottomAnchor constant:14],
    ]];
    previous = errLabel;
  } else {
    NSTextField *updated =
        [self label:updatedText size:11 weight:NSFontWeightRegular color:[NSColor secondaryLabelColor]];
    updated.translatesAutoresizingMaskIntoConstraints = NO;
    [self.content addSubview:updated];
    [NSLayoutConstraint activateConstraints:@[
      [updated.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:16],
      [updated.topAnchor constraintEqualToAnchor:previous.bottomAnchor constant:4],
    ]];
    previous = updated;

    NSArray *meters = result[@"meters"] ?: @[];
    for (NSDictionary *meter in meters) {
      NSView *row = [self meterRow:meter];
      row.translatesAutoresizingMaskIntoConstraints = NO;
      [self.content addSubview:row];
      [NSLayoutConstraint activateConstraints:@[
        [row.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:16],
        [row.trailingAnchor constraintEqualToAnchor:self.content.trailingAnchor constant:-16],
        [row.heightAnchor constraintEqualToConstant:54],
        [row.topAnchor constraintEqualToAnchor:previous.bottomAnchor constant:8],
      ]];
      previous = row;
    }
  }

  // Pin the last content view above the footer.
  [NSLayoutConstraint activateConstraints:@[
    [footer.topAnchor constraintGreaterThanOrEqualToAnchor:previous.bottomAnchor constant:10],
  ]];
}

- (NSView *)meterRow:(NSDictionary *)meter {
  NSView *row = [[NSView alloc] initWithFrame:NSZeroRect];
  // No fill — flat, linear, separated by whitespace alone.

  NSString *labelText = meter[@"label"] ?: @"Usage";
  NSNumber *percentNumber = meter[@"percent"] ?: @0;
  NSString *detailText = meter[@"detail"] ?: @"";
  double percent = MAX(0, MIN(100, percentNumber.doubleValue));

  NSTextField *label = [self label:[NSString stringWithFormat:@"%@  %.0f%%", labelText, percent]
                              size:12 weight:NSFontWeightSemibold color:[NSColor labelColor]];
  NSTextField *detail = [self label:detailText size:11 weight:NSFontWeightRegular color:[NSColor secondaryLabelColor]];
  NSProgressIndicator *progress = [[NSProgressIndicator alloc] initWithFrame:NSZeroRect];
  progress.indeterminate = NO;
  progress.minValue = 0;
  progress.maxValue = 100;
  progress.doubleValue = percent;
  progress.controlSize = NSControlSizeSmall;

  label.translatesAutoresizingMaskIntoConstraints = NO;
  detail.translatesAutoresizingMaskIntoConstraints = NO;
  progress.translatesAutoresizingMaskIntoConstraints = NO;
  [row addSubview:label];
  [row addSubview:detail];
  [row addSubview:progress];

  [NSLayoutConstraint activateConstraints:@[
    [label.leadingAnchor constraintEqualToAnchor:row.leadingAnchor],
    [label.topAnchor constraintEqualToAnchor:row.topAnchor constant:8],
    [detail.trailingAnchor constraintEqualToAnchor:row.trailingAnchor],
    [detail.centerYAnchor constraintEqualToAnchor:label.centerYAnchor],
    [detail.leadingAnchor constraintGreaterThanOrEqualToAnchor:label.trailingAnchor constant:8],
    [progress.leadingAnchor constraintEqualToAnchor:row.leadingAnchor],
    [progress.trailingAnchor constraintEqualToAnchor:row.trailingAnchor],
    [progress.topAnchor constraintEqualToAnchor:label.bottomAnchor constant:8],
    [progress.heightAnchor constraintEqualToConstant:8],
  ]];
  return row;
}

// ---------- settings view ----------

- (void)renderSettings {
  for (NSView *view in [self.content.subviews copy]) {
    [view removeFromSuperview];
  }
  [self.fieldInputs removeAllObjects];

  NSString *active = self.state[@"active"] ?: @"";
  NSString *titleText = @"Usage";
  for (NSDictionary *provider in self.state[@"providers"]) {
    if ([provider[@"id"] isEqualToString:active]) {
      titleText = provider[@"label"] ?: @"Usage";
      break;
    }
  }

  NSView *headerRow = [self makeHeaderRowWithTitle:titleText];
  headerRow.translatesAutoresizingMaskIntoConstraints = NO;
  [self.content addSubview:headerRow];
  [NSLayoutConstraint activateConstraints:@[
    [headerRow.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:0],
    [headerRow.trailingAnchor constraintEqualToAnchor:self.content.trailingAnchor constant:0],
    [headerRow.topAnchor constraintEqualToAnchor:self.content.topAnchor constant:0],
  ]];

  NSDictionary *creds = self.state[@"credentials"][active] ?: @{};
  NSArray *fields = [self fieldsForProvider:active];
  NSView *previous = headerRow;
  for (NSDictionary *fieldDef in fields) {
    NSString *field = fieldDef[@"field"];
    NSString *labelText = fieldDef[@"label"];
    BOOL secure = [fieldDef[@"secure"] boolValue];

    NSTextField *fieldLabel =
        [self label:labelText size:11 weight:NSFontWeightMedium color:[NSColor labelColor]];
    fieldLabel.translatesAutoresizingMaskIntoConstraints = NO;
    [self.content addSubview:fieldLabel];

    NSTextField *input = secure ? [[NSSecureTextField alloc] initWithFrame:NSZeroRect]
                                : [[NSTextField alloc] initWithFrame:NSZeroRect];
    input.stringValue = creds[field] ?: @"";
    input.translatesAutoresizingMaskIntoConstraints = NO;
    input.placeholderString = labelText;
    input.controlSize = NSControlSizeSmall;
    [self.content addSubview:input];
    self.fieldInputs[field] = input;

    [NSLayoutConstraint activateConstraints:@[
      [fieldLabel.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:16],
      [fieldLabel.topAnchor constraintEqualToAnchor:previous.bottomAnchor constant:12],
      [input.leadingAnchor constraintEqualToAnchor:fieldLabel.leadingAnchor],
      [input.trailingAnchor constraintEqualToAnchor:self.content.trailingAnchor constant:-16],
      [input.topAnchor constraintEqualToAnchor:fieldLabel.bottomAnchor constant:4],
    ]];
    previous = input;
  }

  // Save button.
  NSButton *saveButton = [NSButton buttonWithTitle:@"Save & Refresh"
                                             target:self
                                            action:@selector(saveClicked:)];
  saveButton.controlSize = NSControlSizeSmall;
  saveButton.translatesAutoresizingMaskIntoConstraints = NO;
  [self.content addSubview:saveButton];
  [NSLayoutConstraint activateConstraints:@[
    [saveButton.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:16],
    [saveButton.topAnchor constraintEqualToAnchor:previous.bottomAnchor constant:14],
  ]];

  // Footer.
  NSView *footer = [self makeFooterRow];
  footer.translatesAutoresizingMaskIntoConstraints = NO;
  [self.content addSubview:footer];
  [NSLayoutConstraint activateConstraints:@[
    [footer.leadingAnchor constraintEqualToAnchor:self.content.leadingAnchor constant:0],
    [footer.trailingAnchor constraintEqualToAnchor:self.content.trailingAnchor constant:0],
    [footer.bottomAnchor constraintEqualToAnchor:self.content.bottomAnchor constant:0],
    [footer.topAnchor constraintGreaterThanOrEqualToAnchor:saveButton.bottomAnchor constant:10],
  ]];
}

- (NSArray *)fieldsForProvider:(NSString *)provider {
  if ([provider isEqualToString:@"opencode"]) {
    return @[
      @{@"field": @"workspace_id", @"label": @"Workspace ID", @"secure": @NO},
      @{@"field": @"auth_cookie", @"label": @"Auth Cookie", @"secure": @YES},
    ];
  }
  if ([provider isEqualToString:@"codex"]) {
    return @[
      @{@"field": @"api_key", @"label": @"API Key", @"secure": @YES},
      @{@"field": @"org_id", @"label": @"Organization ID", @"secure": @NO},
    ];
  }
  return @[ @{@"field": @"api_key", @"label": @"API Key", @"secure": @YES} ];
}

// ---------- shared subviews ----------

- (NSView *)makeHeaderRowWithTitle:(NSString *)titleText {
  NSView *row = [[NSView alloc] initWithFrame:NSZeroRect];
  row.translatesAutoresizingMaskIntoConstraints = NO;

  NSTextField *title =
      [self label:titleText size:15 weight:NSFontWeightBold color:[NSColor labelColor]];
  title.translatesAutoresizingMaskIntoConstraints = NO;
  [row addSubview:title];

  NSButton *gear =
      [NSButton buttonWithTitle:@"" target:self action:@selector(toggleSettings:)];
  // Toggle icon: gear when on usage view, chart when on settings view.
  NSString *symbol = self.settingsVisible ? @"chart.bar.fill" : @"gearshape";
  gear.image = [NSImage imageWithSystemSymbolName:symbol accessibilityDescription:symbol];
  gear.imagePosition = NSImageOnly;
  gear.bordered = NO;
  gear.contentTintColor = [NSColor secondaryLabelColor];
  gear.translatesAutoresizingMaskIntoConstraints = NO;
  [row addSubview:gear];

  [NSLayoutConstraint activateConstraints:@[
    [title.leadingAnchor constraintEqualToAnchor:row.leadingAnchor constant:16],
    [title.topAnchor constraintEqualToAnchor:row.topAnchor constant:14],
    [gear.trailingAnchor constraintEqualToAnchor:row.trailingAnchor constant:-12],
    [gear.centerYAnchor constraintEqualToAnchor:title.centerYAnchor],
    [gear.widthAnchor constraintEqualToConstant:24],
    [gear.heightAnchor constraintEqualToConstant:24],
    [row.heightAnchor constraintGreaterThanOrEqualToConstant:44],
  ]];
  return row;
}

- (NSView *)makeFooterRow {
  NSView *row = [[NSView alloc] initWithFrame:NSZeroRect];
  row.translatesAutoresizingMaskIntoConstraints = NO;

  // Hairline top border separates the footer from content above.
  NSView *topLine = [[NSView alloc] initWithFrame:NSZeroRect];
  topLine.translatesAutoresizingMaskIntoConstraints = NO;
  topLine.wantsLayer = YES;
  topLine.layer.backgroundColor = [NSColor separatorColor].CGColor;
  [row addSubview:topLine];

  NSButton *refresh =
      [NSButton buttonWithTitle:@"Refresh" target:self action:@selector(refreshClicked:)];
  refresh.bezelStyle = NSBezelStyleAccessoryBar;
  refresh.controlSize = NSControlSizeSmall;
  refresh.translatesAutoresizingMaskIntoConstraints = NO;
  [row addSubview:refresh];

  NSButton *quit = [NSButton buttonWithTitle:@"Quit" target:self action:@selector(quitClicked:)];
  quit.bezelStyle = NSBezelStyleAccessoryBar;
  quit.controlSize = NSControlSizeSmall;
  quit.translatesAutoresizingMaskIntoConstraints = NO;
  [row addSubview:quit];

  [NSLayoutConstraint activateConstraints:@[
    [topLine.leadingAnchor constraintEqualToAnchor:row.leadingAnchor],
    [topLine.trailingAnchor constraintEqualToAnchor:row.trailingAnchor],
    [topLine.topAnchor constraintEqualToAnchor:row.topAnchor],
    [topLine.heightAnchor constraintEqualToConstant:1],
    [refresh.leadingAnchor constraintEqualToAnchor:row.leadingAnchor constant:12],
    [refresh.topAnchor constraintEqualToAnchor:topLine.bottomAnchor constant:6],
    [quit.trailingAnchor constraintEqualToAnchor:row.trailingAnchor constant:-12],
    [quit.centerYAnchor constraintEqualToAnchor:refresh.centerYAnchor],
    [row.heightAnchor constraintEqualToConstant:32],
  ]];
  return row;
}

- (NSTextField *)label:(NSString *)text size:(CGFloat)size weight:(NSFontWeight)weight color:(NSColor *)color {
  NSTextField *label = [NSTextField labelWithString:text ?: @""];
  label.font = [NSFont systemFontOfSize:size weight:weight];
  label.textColor = color;
  label.lineBreakMode = NSLineBreakByTruncatingTail;
  label.translatesAutoresizingMaskIntoConstraints = NO;
  return label;
}

// ---------- actions ----------

- (void)providerClicked:(NSButton *)sender {
  NSString *provider = sender.identifier;
  if (provider.length == 0) {
    return;
  }
  // Switching provider returns to the usage view.
  self.settingsVisible = NO;
  goProviderSelected(provider.UTF8String);
}

- (void)toggleSettings:(id)sender {
  self.settingsVisible = !self.settingsVisible;
  [self renderAll];
}

- (void)refreshClicked:(id)sender {
  goRefreshRequested();
}

- (void)quitClicked:(id)sender {
  goQuitRequested();
  [NSApp terminate:nil];
}

- (void)saveClicked:(id)sender {
  NSString *active = self.state[@"active"] ?: @"";
  NSArray *fields = [self fieldsForProvider:active];
  for (NSDictionary *fieldDef in fields) {
    NSString *field = fieldDef[@"field"];
    NSTextField *input = self.fieldInputs[field];
    if (input == nil) {
      continue;
    }
    goSaveCredentials(active.UTF8String, field.UTF8String, input.stringValue.UTF8String);
  }
  self.settingsVisible = NO;
}

@end

// ---------------------------------------------------------------------------
// AppDelegate: owns the NSStatusItem and the NSPopover.
// ---------------------------------------------------------------------------

@interface OCGAppDelegate : NSObject <NSApplicationDelegate>
@property(strong) NSStatusItem *statusItem;
@property(strong) NSPopover *popover;
@property(strong) UsagePanelController *controller;
@end

@implementation OCGAppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)note {
  [[NSProcessInfo processInfo] disableAutomaticTermination:@"OCG menu bar monitor"];

  self.statusItem =
      [[NSStatusBar systemStatusBar] statusItemWithLength:NSVariableStatusItemLength];
  self.statusItem.button.target = self;
  self.statusItem.button.action = @selector(togglePopover:);
  // No icon until the first refresh pushes a template gauge icon.

  self.controller = [[UsagePanelController alloc] init];
  self.popover = [[NSPopover alloc] init];
  self.popover.contentViewController = self.controller;
  self.popover.behavior = NSPopoverBehaviorTransient;
  self.popover.animates = YES;

  // Hand off to the Go data layer — starts the background refresh loop.
  goOnReady();
}

- (void)togglePopover:(id)sender {
  if (self.popover.shown) {
    [self.popover performClose:nil];
    return;
  }
  [self.popover showRelativeToRect:self.statusItem.button.bounds
                            ofView:self.statusItem.button
                     preferredEdge:NSMinYEdge];
  [NSApp activateIgnoringOtherApps:YES];
}

- (void)setStatusIconBytes:(const void *)bytes length:(size_t)length {
  NSData *data = [NSData dataWithBytes:bytes length:length];
  NSImage *image = [[NSImage alloc] initWithData:data];
  if (image == nil) {
    return;
  }
  // Template image: AppKit tints it to match the menu bar (dark/light).
  image.template = YES;
  dispatch_async(dispatch_get_main_queue(), ^{
    self.statusItem.button.image = image;
    self.statusItem.button.imagePosition = NSImageOnly;
  });
}

- (void)setTooltip:(NSString *)tooltip {
  dispatch_async(dispatch_get_main_queue(), ^{
    self.statusItem.button.toolTip = tooltip;
  });
}

- (void)updateWithStateJSON:(NSString *)json {
  dispatch_async(dispatch_get_main_queue(), ^{
    [self.controller updateWithStateJSON:json];
  });
}

@end

// ---------------------------------------------------------------------------
// C entry points invoked from Go (all marshal to the main queue).
// ---------------------------------------------------------------------------

static OCGAppDelegate *ocgAppDelegate = nil;

void runApp(void) {
  @autoreleasepool {
    NSApplication *app = [NSApplication sharedApplication];
    ocgAppDelegate = [[OCGAppDelegate alloc] init];
    app.delegate = ocgAppDelegate;
    [app run];
  }
}

void setStatusIcon(const void *bytes, size_t length) {
  @autoreleasepool {
    [ocgAppDelegate setStatusIconBytes:bytes length:length];
  }
}

void setStatusTooltip(const char *tooltip) {
  @autoreleasepool {
    [ocgAppDelegate setTooltip:[NSString stringWithUTF8String:tooltip ?: ""]];
  }
}

void updatePanelState(const char *stateJSON) {
  @autoreleasepool {
    [ocgAppDelegate updateWithStateJSON:[NSString stringWithUTF8String:stateJSON ?: ""]];
  }
}
